# 1-D Array

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


# 2-D Array

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


# Initialize the elements of x X y  array to 0

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Arrange the numbers between x and y with the interval of z

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
# even numbers between the 10 and 20 
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

# Arrange 'z' numbers between x and y

In [9]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [11]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

# Filling SAME number in an array of dimension x X y

In [12]:
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

In [13]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

# Filling RANDOM number in an array of dimension x X y

In [14]:
np.random.random((2,3))

array([[0.36838677, 0.06879341, 0.10610623],
       [0.99631154, 0.42305867, 0.90326411]])

In [15]:
np.random.random((3,5))

array([[0.34781505, 0.95765786, 0.11699527, 0.45444952, 0.73799336],
       [0.57230766, 0.55879323, 0.69336052, 0.45429343, 0.85767294],
       [0.28634995, 0.94865281, 0.44294835, 0.78907385, 0.41983894]])

# Inspecting the  array: Checking the size of the array

In [18]:
a = np.array([[2,4,6],[5,3,4]])
print(a.shape)

(2, 3)


In [19]:
s = np.array([[2,5,7,4],[3,8,6,3],[2,4,8,6]])
print(s.shape)

(3, 4)


# Inspecting the array: Resize the array

In [21]:
a = np.array([[2,4,6],[5,3,4]])
a.shape = (3,2)
print(a)

[[2 4]
 [6 5]
 [3 4]]


# Return the dimension of the array

In [22]:
a = np.arange(24)
a
print(a.ndim)
#reshape our array
b = a.reshape(2,4,3) #trick: calculate the factor of 24: 1,2,3,4,6,12,24
print(b.ndim)
b

1
3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

# Find the number of elements in the array

In [23]:
print(a.size)

24


# Find the datatype of the array

In [24]:
a = np.array(24, dtype=float)
print(a.dtype)
a

float64


array(24.)

# Numpy array Mathematics

In [25]:
np.sum([10,20])

30

In [26]:
#using the variable
a,b = 10,20
np.sum([a,b])

30

In [28]:
np.sum([[1,4],[5,7]], axis = 0)

array([ 6, 11])

In [29]:
np.sum([[1,4],[5,7]])

17

In [30]:
np.subtract(20,10)

10

In [31]:
np.multiply(2,6)

12

In [32]:
np.divide(6,2)

3.0

In [34]:
a = np.array([4,8,24])
b = np.array([2,4,12])
np.divide(a,b)

array([2., 2., 2.])

In [35]:
#np.exp, np.sqrt, np.sin, np.cos, np.log

# Array Comparison

In [37]:
#Element wise comparison
a = [1,2,3]
b = [3,2,6]
c = [1,2,3]
g=np.equal(a,b)
h=np.equal(a,c)
print(g,h)

[False  True False] [ True  True  True]


In [38]:
# Array-wise comparison
a = [1,2,4]
b= [3,5,6]
c = [1,2,4]
j=np.array_equal(a,b)
i=np.array_equal(a,c)
print(j,i)

False True


# Broadcasting

In [39]:
a = np.array([[1,1,1], [4,6,3], [7,4,7]])
b = np.array([3,5,6])
print(a+b)

[[ 4  6  7]
 [ 7 11  9]
 [10  9 13]]


# Array Manipulation in python

In [40]:
a = [2,5,6]
b = [3,5,7]
#concatination of two array
np.concatenate((a,b))

array([2, 5, 6, 3, 5, 7])

In [41]:
# Stack array row-wise: Horizontal
np.hstack((a,b))

array([2, 5, 6, 3, 5, 7])

In [42]:
# Stack array row-wise: Vertically
np.vstack((a,b))

array([[2, 5, 6],
       [3, 5, 7]])

In [43]:
# Combining Column-wise
np.column_stack((a,b))

array([[2, 3],
       [5, 5],
       [6, 7]])

# Splitting Array

In [48]:
x = np.arange(16).reshape(4,4)
print(x)
print(np.hsplit(x,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [50]:
print(np.hsplit(x, np.array([2,3])))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


# Indexing and Slicing

In [52]:
a = np.array([[2,4,6],[6,3,6]])
a[0]
a[:3]
print(a)
a[:1,1:]

[[2 4 6]
 [6 3 6]]


array([[4, 6]])