# Loading Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

iris = pd.read_csv("iris.csv")
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
x = pd.DataFrame(iris[['sepal_length','sepal_width','petal_length','petal_width']])
y = pd.DataFrame(iris['species'])

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

# Building the Model

In [45]:
# Building the decision tree classifier
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [46]:
y_pred = classifier.predict(x_test)

In [47]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


In [48]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9555555555555556
