# Loading the data

In [1]:
# Importing required libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
dataset = pd.read_csv('iris.csv')
dataset.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [8]:
X = dataset.drop('species',1)
y = dataset['species']
y.head()

C:\Users\SHUBHAM KUMAR\AppData\Local\Temp\ipykernel_12500\4236175572.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = dataset.drop('species',1)


0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object

In [9]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

# Building the Model

In [10]:
# splitting the data
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)

In [11]:
sc = StandardScaler() #for eliminating outliers
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
#loading the model
pca = PCA()
X_train = pca.fit_transform(X_train) #fit_transform will learn from training dataset which variables to take
X_test = pca.transform(X_test) # because it has learned from training set so we use directly transform

In [15]:
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.72226528, 0.23974795, 0.03338117, 0.0046056 ])

In [20]:
def perform_pca(n):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0)
    pca = PCA(n_components=n)
    pca_x_train = pca.fit_transform(X_train)
    pca_x_test = pca.transform(X_test)
    classifier = RandomForestClassifier(max_depth=2, random_state=0)
    classifier.fit(pca_x_train, y_train)
    y_pred = classifier.predict(pca_x_test)
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    print('Accuracy:', accuracy_score(y_test, y_pred))

In [21]:
for x in range(1,5): perform_pca(x)

[[11  0  0]
 [ 0 12  1]
 [ 0  2  4]]
Accuracy: 0.9
[[11  0  0]
 [ 0  8  5]
 [ 0  1  5]]
Accuracy: 0.8
[[11  0  0]
 [ 0  5  8]
 [ 0  1  5]]
Accuracy: 0.7
[[11  0  0]
 [ 0 11  2]
 [ 0  1  5]]
Accuracy: 0.9
